from Monte_carlo import MonteCarloMethode

ligand = 'c1ccccc1'
protein_bromo = ['SMNPPPPETSNPNKPKRQTNQLQYLLRVVLKTLWKHQFAWPFQQPVDAVKLNLPDYYKIIKTPMDMGTIKKRLENNYYWNAQECIQDFNTMFTNCYIYNKPGDDIVLMAEALEKLFLQKINELPTEE ']
protein_serine = ['MAHHHHHHLEVLFQGPLLSKINSLAHLRAAPCNDLHATKLAPGKEKEPLESQYQVGPLLGSGGFGSVYSGIRVSDNLPVAIKHVEKDRISDWGELPNGTRVPMEVVLL'
           'KKVSSGFSGVIRLLDWFERPDSFVLILERPEPVQDLFDFITERGALQEELARSFFWQVLEAVRHCHNCGVLHRDIKDENILIDLNRGELKLIDFGSGALLKDTVYTDF'
           'DGTRVYSPPEWIRYHRYHGRSAAVWSLGILLYDMVCGDIPFEHDEEIIRGQVFFRQRVSSECQHLIRWCLALRPSDRPTFEEIQNHPWMQDVLLPQETAEIHLHSLSPGPSK']
protein_p38 = ['GSHMLEMSQERPTFYRQELNKTIWEVPERYQNLSPVGSGAYGSVCAAFDTKTGLRVAVKKLSRPFQSIIHAKRTYRELRLLKHMKHENVIGLLDVFTPARSLEEFNDV'
           'YLVTHLMGADLNNIVKCQKLTDDHVQFLIYQILRGLKYIHSADIIHRDLKPSNLAVNEDSELKILDFGLARHTDDEMTGYVATRWYRAPEIMLNWMHYNQTVDIWSVG'
           'CIMAELLTGRTLFPGTDHIDQLKLILRLVGTPGAELLKKISSESARNYIQSLTQMPKMNFANVFIGANPLAVDLLEKMLVLDSDKRITAAQALAHAYFAQYHDPDDEP'
           'VADPYDQSFESRDLLIDEWKSLTYDEVISFVPPPLDQEEMES']
protein_cohE = ['TLVPVISWVQAGAWKEVGYSEVDLSTAETYPCPVPCGEMTYILRVIGDSMIDEYRPGDMIFVDPEVPACHGDDVIALMHDTGETTFKRLIEDGTQRYLKALNPNWPEPYIKINGNCSIIGTVIFSGKPRRYKIKA']
protein_murC = ['MNTQQLAKLRSIVPEMRRVRHIHFVGIGGAGMGGIAEVLANEGYQISGSDLAPNPVTQQLMNLGATIYFNHRPENVRDASVVVVSSAISADNPEIVAAHEARI'
                'PVIRRAEMLAELMRFRHGIAIAGTHGKTTTTAMVSSIYAEAGLDPTFVNGGLVKAAGVHARLGHGRYLIAEADESDASFLHLQPMVAIVTNIEADHMDTYQGD'
                'FENLKQTFINFLHNLPFYGRAVMCVDDPVIRELLPRVGRQTTTYGFSEDADVRVEDYQQIGPQGHFTLLRQDKEPMRVTLNAPGRHNALNAAAAVAVATEEGI'
                'DDEAILRALESFQGTGRRFDFLGEFPLEPVNGKSGTAMLVDDYGHHPTEVDATIKAARAGWPDKNLVMLFQPHRFTRTRDLYDDFANVLTQVDTLLMLEVYPA'
                'GEAPIPGADSRSLCRTIRGRGKIDPILVPDPARVAEMLAPVLTGNDLILVQGAGNIGKIARSLAEIKLKPQTPEEEQHD']
protein_cdsA = ['MLKYRLISAFVLIPVVIAALFLLPPVGFAIVTLVVCMLAAWEWGQLSGFTTRSQRVWLAVLCGLLLALMLFLLPEYHRNIHQPLVEISLWASLGWWIVALLLV'
                'LFYPGSAAIWRNSKTLRLIFGVLTIVPFFWGMLALRAWHYDENHYSGAIWLLYVMILVWGADSGAYMFGKLFGKHKLAPKVSPGKTWQGFIGGLATAAVISWG'
                'YGMWANLDVAPVTLLICSIVAALASVLGDLTESMFKREAGIKDSGHLIPGHGGILDRIDSLTAAVPVFACLLLLVFRTL']

protein = protein_serine
example = MonteCarloMethode(protein, ligand, f'./serine_a1.txt')
best = example.monte_carlo_full(2000, 50)[0]


